### ISSUE TITLE
Add # of attempts to /wr stats

### ISSUE THREAD

**Issue by Belastigen** [SlidyBat/Timer#4]
Have it so that when you do /wr and check the stats for the record you're checking, it shows number of times the player has attempted the map, probably just number of restarts/times they've exited start zone.

Could be used to validate/invalidate runs, (if someone lands global record in like 1 try, for instance) as well as giving peace of mind to people who are struggling, who can then look to see the wr holder tried over 500 times or something before landing their run.

**Comment by SlidyBat** [comment]
Added, let me know if there are any issues with it.
